/* src/utils/glossary.js */

export const TERMINOLOGY = {
  WORKSHOP: {
    MISSIONS_HEADER: "OPERATIONAL MILESTONES",
    BOM_HEADER: "RESOURCE ALLOCATION",
    NOTES_LABEL: "TECHNICAL LOGS",
    TAGS_LABEL: "SYSTEM TAGS",
    HUB_HEADER: "WORKSHOP",
    HUB_SUBTITLE: "R&D OPERATIONS"
  },
  INVENTORY: {
    HEADER: "SUPPLY LOCKER",
    MANIFEST_LABEL: "MATERIAL MANIFEST"
  },
  MARKET: {
    HEADER: "MARKET RADAR",
    SUBTITLE: "COMPETITIVE INTELLIGENCE",
    PULSE_HEADER: "MARKET PULSE"
  }
};